### ISSUE TITLE
Looping additional key-value pairs

### ISSUE THREAD

**Issue by sanketgandhi** [awslabs/aws-apigateway-lambda-authorizer-blueprints#15]
I'm settting some variables (redis data) in the additional key-value pair. I'm able to access those like `$context.authorizer.key`  in API gateway.

But If I have hundreds of key-value pair then how can I loop it so that it can be pass it to the endpoint.

https://github.com/awslabs/aws-apigateway-lambda-authorizer-blueprints/blob/4920d93a5f67bb445be57b8e1aa88967a036e0e3/blueprints/nodejs/index.js#L66

**Comment by parrik** [comment]
Hi, I have updated the answer here:

https://stackoverflow.com/questions/46934755/how-to-loop-all-the-keys-in-context-authorizer-in-aws-api-gateway 
Hopefully, this should resolve the issue.

Thanks!
