### ISSUE TITLE
Add C# blueprint

### ISSUE THREAD

**Issue by jackrk** [awslabs/aws-apigateway-lambda-authorizer-blueprints#5]

**Comment by adityakatta** [comment]
Can you please look into the C# blueprint. Thanks

**Comment by JoeDM09** [comment]
@jackrk I notice there are two pull requests open for this at the moment which indicates a fair level of community interest to add this blueprint.

I understand that a security team needs to ensure that the code is safe and other teams will need to check if the code is consistent with internal standards, and I am more than happy to make any changes required to get the pull request fulfill these requirements. 

Is there any possibility we can get an update on how this is going?

**Comment by jackrk** [comment]
Resolved by #12
