### ISSUE TITLE
Error in nodejs blueprint?

### ISSUE THREAD

**Issue by carlnordenfelt** [awslabs/aws-apigateway-lambda-authorizer-blueprints#6]
Hi,

I just tried the nodejs blueprint and I think I've come across an error.

When parsing `event.methodArn`, the  `apiGatewayArnTmp` is assigned via:
`tmp[5].split('/')`

Later on (on line 44), when getting the resource, you take `apiGatewayArnTmp[3]`.
If the resource has a slash in it (which it is likely to do since it's a path), you'll only get the first part of the path:

ARN: `arn:aws:execute-api:eu-west-1:1234567890:abc123/*/GET/test/deep/path`
Yeilds: resource: `/test` when it should be `/test/deep/path`

Changing line 43-45 to the following should fix this issue:
```
if (apiGatewayArnTmp[3]) {
    resource += apiGatewayArnTmp.slice(3, apiGatewayArnTmp.length).join('/');
}
```

This will correctly yield resource: `/test/deep/path`

**Comment by jackrk** [comment]
Good point, thanks for pointing that out. Care to submit a PR?

**Comment by carlnordenfelt** [comment]
Sure thing. I'll do it on monday:)

**Comment by jackrk** [comment]
Just merged the PR, sorry for taking so long! Thanks for the contribution!
