### ISSUE TITLE
Calling getPolicyDocument in AuthPolicy.java causing multiple statement duplicates

### ISSUE THREAD

**Issue by grelaxus** [awslabs/aws-apigateway-lambda-authorizer-blueprints#9]
Calling getPolicyDocument in AuthPolicy.java causing multiple statement duplicates in the returned map. If I call it more than one time (e.g. to log some of policyDocument info or to make multiple assertions in tests) the returned Map (and list of statements of PolicyDocument) contains multiple entries of same statements. This is because getStatement() doesn't just get, it actually adds allow and deny statements on every get call.

**Comment by jackrk** [comment]
Thanks for the bug report, care to submit a PR for this? Should be simple I hope.

**Comment by grelaxus** [comment]
@jackrk done.
